spring:
  application:
    name: data
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost/dnd_equipment
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
logging:
  charset:
    file: UTF-8
    console: UTF-8
  file:
    name: logs/application.log
  level:
    root: debug
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
      total-size-cap: 1GB